apiVersion: v2
name: payment-latency-api
description: Payment Latency API - Multi-region fintech payment platform
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - payments
  - fintech
  - latency
maintainers:
  - name: Platform Team
    email: platform.cb@pluxeegroup.com
